# Generated by Django 3.2.7 on 2022-09-18 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220917_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, default='/profile_default.png', null=True, upload_to='users/profile_photos', verbose_name='Profile Photo')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='users/cover_photos', verbose_name='cover Photo')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=20, verbose_name='Gender')),
                ('address_line_1', models.CharField(max_length=100, verbose_name='Adress Line 1')),
                ('address_line_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adress Line 2')),
                ('country', django_countries.fields.CountryField(default='NG', max_length=2, verbose_name='Country')),
                ('state', models.CharField(default='Kano', max_length=50, verbose_name='State')),
                ('city', models.CharField(default='Fagge', max_length=180, verbose_name='City')),
                ('latitude', models.CharField(blank=True, max_length=20, null=True, verbose_name='Latitude')),
                ('longitude', models.CharField(blank=True, max_length=20, null=True, verbose_name='Longitude')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
