# Generated by Django 3.2.7 on 2022-09-18 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(default='Nigeria', max_length=100, verbose_name='Country'),
        ),
    ]
