# Generated by Django 3.2.7 on 2022-09-28 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='address_line_2',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Adress'),
        ),
    ]
